name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.milanese.life
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: git.milanese.life/admin/genealogy-frontend:latest
          build-args: |
            DB_HOST=shared-data_postgres
            DB_PORT=5432
            DB_NAME=genealogy
            DB_USER=genealogy
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Deploy to Swarm
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          MANAGER_HOST: ${{ secrets.SWARM_MANAGER_HOST }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $MANAGER_HOST >> ~/.ssh/known_hosts 2>/dev/null

          # Pull new image and update service
          ssh -o StrictHostKeyChecking=no peterm@$MANAGER_HOST "docker pull git.milanese.life/admin/genealogy-frontend:latest && docker service update --image git.milanese.life/admin/genealogy-frontend:latest --force genealogy_genealogy"

