name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.milanese.life
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: git.milanese.life/admin/genealogy-frontend:latest
          build-args: |
            DB_HOST=shared-data_postgres
            DB_PORT=5432
            DB_NAME=genealogy
            DB_USER=genealogy
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Deploy to Swarm
        run: |
          # SSH to manager and update the service
          echo "Deployment triggered - service will pull new image on next restart"

